### PR TITLE
Create diagrams.md

### PR DESCRIPTION
**Pull request by delas6006**
Flowchart

### CODE REVIEW

**Comment by Laura-Novich-OBW** [comment]
Hi Debbie
In cases where you are making a decision
Do I work out
Do I take the bus
these items need to be in a diamond where there is a yes route and a no route.
Otherwise the workflow should be linear

**Comment by delas6006** [comment]
Hi Laura

Thank you, and I changed the shapes.

Regards
Debbie

**Comment by Laura-Novich-OBW** [comment]
see my comment in the classroom

**Review by Laura-Novich-OBW — CHANGES_REQUESTED** [review]
Debbie the logic doesn't make sense please change the diagram

1. Does the time you wake up depend on if you're exercising or not?
2. How do you decide to take the car or the bus?
3. You laid out your clothes but you never got dressed. I am assuming you're not going to work naked. 
Any action which you do needs to be inside a [ ] any decision you make needs to be in { }

**Comment by Laura-Novich-OBW** [comment]
Debbie, there is an issue with your logic. Look at the diagram and follow the entire path. If you do not see the issue, please let me know,

**Comment by delas6006** [comment]
Hi Laura

Shavuo Tov

I hope you are well.

I have completed part of the final project.
https://github.com/delas6006/Debbie-Mankowitz-showcase-/blob/main/README.md
Just wanted to check that I am on the right track.
I now have to complete the POST part of the assignment.

Also, I did open up Trello for you to see.

I also tried to fix up the logic in the diagram assignment.

Thank you so much,


Best regards
Debbie

**Comment by delas6006** [comment]
Hi Laura

I hope you are feeling a bit better.
This is my GitHub link for the final API project when you have time.

https://github.dev/delas6006/Debbie-Mankowitz-showcase-/tree/GPMD


Regards

Debbie

**Comment by Laura-Novich-OBW** [comment]
Debbie something is still not right.
Please do the following
1. DRAW your flowchart on paper.
2. Send it to me via WhatsApp or email
3. Discuss and I'll show you how to translate the picture to code.

**Review by Laura-Novich-OBW — APPROVED** [review]

**Comment by Laura-Novich-OBW** [comment]
please upload a screenshot to google classroom

**Pull request merged**
