### PR TITLE
Create mermaid-morning-routine.md for Sharon

### PR DESCRIPTION
**Pull request by Schnee18**
Sharon's mermaid flow chart

### CODE REVIEW

**Comment by lsnovich** [comment]
Sharon, 
Nice job
Sequence diagrams focus more on the action (do this) than the reason (this looks nice)
so if you can, please remove all the fluff from the workflow.

**Review by lsnovich — CHANGES_REQUESTED** [review]
see comment

**Comment by Schnee18** [comment]
Hi Laura, I made changes to the sequence diagram. Please review.

**Comment by lsnovich** [comment]
much better!
Merging - please add a screenshot to Google Classroom

**Review by lsnovich — APPROVED** [review]

**Pull request merged**
